services:
  - type: web
    name: epi-controle
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: OCR_REQUIRED
        value: "1"
