import threading
import re

from epi_backend.config import (
    DATABASE_URL,
    DB_CONNECTOR_AVAILABLE,
    DB_POOL_MAXCONN,
    DB_POOL_MINCONN,
    DictCursor,
    psycopg2_pool,
)

_CONNECTION_POOL = None
_CONNECTION_POOL_LOCK = threading.Lock()

# Tables known to lack an `id` column. INSERTs into these must not append
# `RETURNING id` (Postgres rejects it with `column "id" does not exist`, which
# the server also records as an ERROR in the logs). We learn them lazily on the
# first failed attempt and skip the RETURNING shim from then on.
_TABLES_WITHOUT_ID: set = set()
_TABLES_WITHOUT_ID_LOCK = threading.Lock()


def _insert_target_table(sql: str):
    match = re.match(r'\s*INSERT\s+INTO\s+"?([A-Za-z_][A-Za-z0-9_]*)"?', sql, re.IGNORECASE)
    return match.group(1).lower() if match else None


class PostgresCursorWrapper:
    def __init__(self, cursor, inserted_id=None):
        self._cursor = cursor
        self.lastrowid = inserted_id

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class PostgresConnectionWrapper:
    def __init__(self, connection, release_hook=None):
        self._connection = connection
        self._release_hook = release_hook
        self._released = False

    def _normalize_sql(self, query):
        normalized = str(query)
        normalized = re.sub(
            r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            normalized,
            flags=re.IGNORECASE,
        )
        normalized = self._replace_qmark_params(normalized)
        return normalized

    @staticmethod
    def _replace_qmark_params(query: str) -> str:
        """Replace `?` placeholders with `%s` and escape bare `%` as `%%`.

        psycopg2 interprets every `%` in the SQL string as a format placeholder
        when params are provided (even an empty tuple). SQL that contains `%I` or
        `%L` (PostgreSQL format() specifiers) or `%` in LIKE patterns embedded
        directly in the query string must be escaped as `%%` so psycopg2 passes
        them through as literal `%` to PostgreSQL.  Only `?` → `%s` substitutions
        are intended as actual bind parameters.
        """
        result = []
        in_single_quote = False
        in_double_quote = False
        escape_next = False
        for ch in str(query):
            if escape_next:
                result.append(ch)
                escape_next = False
                continue
            if ch == "\\":
                result.append(ch)
                escape_next = True
                continue
            if ch == "'" and not in_double_quote:
                in_single_quote = not in_single_quote
                result.append(ch)
                continue
            if ch == '"' and not in_single_quote:
                in_double_quote = not in_double_quote
                result.append(ch)
                continue
            if ch == "?" and not in_single_quote and not in_double_quote:
                result.append("%s")
                continue
            if ch == "%":
                result.append("%%")
                continue
            result.append(ch)
        return "".join(result)

    def execute(self, query, params=None):
        sql = self._normalize_sql(query)
        cursor = self._connection.cursor(cursor_factory=DictCursor)
        inserted_id = None
        is_insert = sql.lstrip().upper().startswith("INSERT INTO ") and " RETURNING " not in sql.upper()
        target_table = _insert_target_table(sql) if is_insert else None
        if is_insert and target_table not in _TABLES_WITHOUT_ID:
            returning_sql = sql.rstrip().rstrip(";") + " RETURNING id"
            try:
                cursor.execute("SAVEPOINT sp_insert_returning_id")
                cursor.execute(returning_sql, params or ())
                row = cursor.fetchone()
                inserted_id = row[0] if row else None
                cursor.execute("RELEASE SAVEPOINT sp_insert_returning_id")
            except Exception as exc:
                # Precisa acontecer para QUALQUER exceção aqui, não só a
                # tolerada abaixo — sem isso a transação fica "aborted" e um
                # commit() posterior (ex.: depois de um try/except que engole
                # essa exceção, como modules/*/routes.py:_audit) descarta
                # silenciosamente toda a transação, sem levantar erro
                # (issue #177/#842).
                cursor.execute("ROLLBACK TO SAVEPOINT sp_insert_returning_id")
                cursor.execute("RELEASE SAVEPOINT sp_insert_returning_id")
                message = str(exc).lower()
                # SQLSTATE 42703 (undefined_column) é independente de locale;
                # o texto em inglês fica como fallback para drivers/versões
                # que não populem pgcode.
                missing_id_column = (
                    getattr(exc, "pgcode", None) == "42703"
                    or 'column "id" does not exist' in message
                    or "undefinedcolumn" in message
                )
                if not missing_id_column:
                    raise
                if target_table:
                    with _TABLES_WITHOUT_ID_LOCK:
                        _TABLES_WITHOUT_ID.add(target_table)
                cursor.execute(sql, params or ())
        else:
            cursor.execute(sql, params or ())
        return PostgresCursorWrapper(cursor, inserted_id)

    def executemany(self, query, seq_of_params):
        sql = self._normalize_sql(query)
        with self._connection.cursor() as cursor:
            cursor.executemany(sql, seq_of_params)

    def executescript(self, script):
        statements = [item.strip() for item in str(script).split(";") if item.strip()]
        with self._connection.cursor() as cursor:
            for statement in statements:
                cursor.execute(self._normalize_sql(statement))

    def cursor(self):
        return self._connection.cursor(cursor_factory=DictCursor)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        if self._released:
            return
        self._released = True
        if self._release_hook:
            self._release_hook(self._connection)
            return
        self._connection.close()

    def __getattr__(self, name):
        return getattr(self._connection, name)


def get_connection_pool():
    global _CONNECTION_POOL
    if _CONNECTION_POOL:
        return _CONNECTION_POOL
    with _CONNECTION_POOL_LOCK:
        if _CONNECTION_POOL:
            return _CONNECTION_POOL
        if not DB_CONNECTOR_AVAILABLE:
            raise RuntimeError("Instale psycopg2-binary para usar o servidor Postgres/Supabase.")
        if not DATABASE_URL:
            raise RuntimeError("DATABASE_URL nao configurada.")
        _CONNECTION_POOL = psycopg2_pool.SimpleConnectionPool(DB_POOL_MINCONN, DB_POOL_MAXCONN, DATABASE_URL)
        return _CONNECTION_POOL


def release_connection(raw_connection):
    pool = get_connection_pool()
    if not getattr(raw_connection, "closed", False):
        raw_connection.rollback()
    pool.putconn(raw_connection)


def db_pool_status():
    pool = _CONNECTION_POOL
    if not pool:
        return {
            "enabled": DB_CONNECTOR_AVAILABLE and bool(DATABASE_URL),
            "initialized": False,
            "minconn": DB_POOL_MINCONN,
            "maxconn": DB_POOL_MAXCONN,
            "available": 0,
            "in_use": 0,
        }
    return {
        "enabled": True,
        "initialized": True,
        "minconn": DB_POOL_MINCONN,
        "maxconn": DB_POOL_MAXCONN,
        "available": int(len(getattr(pool, "_pool", []) or [])),
        "in_use": int(len(getattr(pool, "_used", {}) or {})),
    }


def get_connection():
    if not DB_CONNECTOR_AVAILABLE:
        raise RuntimeError("Instale psycopg2-binary para usar o servidor Postgres/Supabase.")
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL nao configurada.")
    raw_connection = get_connection_pool().getconn()
    return PostgresConnectionWrapper(raw_connection, release_hook=release_connection)


def row_to_dict(row):
    return {key: row[key] for key in row.keys()}


def _is_sqlite_connection(connection) -> bool:
    module_name = str(getattr(type(connection), '__module__', '')).lower()
    class_name = str(getattr(type(connection), '__name__', '')).lower()
    return 'sqlite' in module_name or 'sqlite' in class_name


def table_exists(connection, table) -> bool:
    """Verifica se uma tabela existe (SQLite ou Postgres). Vive em ``db`` — a
    camada de mais baixo nível — para poder ser usada por qualquer módulo sem
    criar ciclo de importação com ``core.schema``."""
    table_name = str(table or '').strip()
    if not table_name:
        return False
    try:
        if _is_sqlite_connection(connection):
            row = connection.execute(
                "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ? LIMIT 1",
                (table_name,),
            ).fetchone()
            return row is not None
        row = connection.execute(
            "SELECT 1 FROM information_schema.tables WHERE table_name = ? LIMIT 1",
            (table_name,),
        ).fetchone()
        return row is not None
    except Exception:
        return False


def mandatory_db_columns(connection, table: str) -> set[str]:
    """Colunas NOT NULL sem DEFAULT — o banco exige um valor explícito.

    O motor só grava os campos que a linha preencheu. Numa tabela madura
    como ``employees`` há colunas NOT NULL sem default (``sector``) que
    nenhum export legado traz: sem preencher, o INSERT falha no banco. Aqui
    descobrimos quais são para dar-lhes string vazia — o mesmo valor que o
    cadastro manual do próprio sistema grava.
    """
    table_name = str(table or '').strip()
    if not table_name:
        return set()
    try:
        if _is_sqlite_connection(connection):
            rows = connection.execute(f'PRAGMA table_info({table_name})').fetchall()
            return {
                str(row['name'] if isinstance(row, dict) else row[1])
                for row in rows
                if int(row['notnull'] if isinstance(row, dict) else row[3]) == 1
                and (row['dflt_value'] if isinstance(row, dict) else row[4]) is None
                and str(row['name'] if isinstance(row, dict) else row[1]) != 'id'
            }
        rows = connection.execute(
            'SELECT column_name FROM information_schema.columns '
            "WHERE table_name = %s AND is_nullable = 'NO' AND column_default IS NULL",
            (table_name,),
        ).fetchall()
        return {str(row_to_dict(row).get('column_name') or '') for row in rows} - {'id'}
    except Exception:  # introspecção é best-effort, como em table_columns
        return set()


def table_columns(connection, table) -> set:
    """Conjunto de colunas de uma tabela (SQLite ou Postgres). Ver
    ``table_exists`` para a justificativa de residir em ``db``."""
    table_name = str(table or '').strip()
    if not table_name:
        return set()
    try:
        if _is_sqlite_connection(connection):
            rows = connection.execute(f"PRAGMA table_info({table_name})").fetchall()
            return {str(row['name'] if isinstance(row, dict) else row[1]) for row in rows}
        rows = connection.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name = ?",
            (table_name,),
        ).fetchall()
        result = set()
        for row in rows:
            if isinstance(row, dict):
                result.add(str(row.get('column_name') or ''))
            elif hasattr(row, 'keys'):
                result.add(str(row['column_name']))
            else:
                result.add(str(row[0]))
        return {item for item in result if item}
    except Exception:
        return set()
