import os
import threading

from epi_backend.config import DATABASE_URL, DB_CONNECTOR_AVAILABLE
from epi_backend.http_utils import structured_log

try:
    import psycopg2
    from psycopg2 import pool as psycopg2_pool
    from psycopg2.extras import DictCursor
except ModuleNotFoundError:
    psycopg2 = None
    psycopg2_pool = None
    DictCursor = None

DB_POOL_MINCONN = int(os.environ.get('DB_POOL_MINCONN', '1'))
DB_POOL_MAXCONN = int(os.environ.get('DB_POOL_MAXCONN', '10'))

_CONNECTION_POOL = None
_CONNECTION_POOL_LOCK = threading.Lock()


class LegacyPostgresCursorWrapper:
    def __init__(self, cursor, inserted_id=None):
        self._cursor = cursor
        self.lastrowid = inserted_id

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class PostgresConnectionWrapper:
    def __init__(self, connection, release_hook=None):
        self._connection = connection
        self._release_hook = release_hook
        self._released = False

    def _normalize_sql(self, query):
        normalized = str(query)
        normalized = normalized.replace('INTEGER PRIMARY KEY AUTOINCREMENT', 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        normalized = normalized.replace('?', '%s')
        return normalized

    def execute(self, query, params=None):
        sql = self._normalize_sql(query)
        cursor = self._connection.cursor(cursor_factory=DictCursor)
        inserted_id = None
        if sql.lstrip().upper().startswith('INSERT INTO ') and ' RETURNING ' not in sql.upper():
            returning_sql = sql.rstrip().rstrip(';') + ' RETURNING id'
            try:
                cursor.execute('SAVEPOINT sp_insert_returning_id')
                cursor.execute(returning_sql, params or ())
                row = cursor.fetchone()
                inserted_id = row[0] if row else None
                cursor.execute('RELEASE SAVEPOINT sp_insert_returning_id')
            except Exception as exc:
                message = str(exc).lower()
                if 'column "id" does not exist' not in message and 'undefinedcolumn' not in message:
                    raise
                cursor.execute('ROLLBACK TO SAVEPOINT sp_insert_returning_id')
                cursor.execute('RELEASE SAVEPOINT sp_insert_returning_id')
                cursor.execute(sql, params or ())
        else:
            if params is not None:
                cursor.execute(sql, params)
            else:
                cursor.execute(sql)
        return LegacyPostgresCursorWrapper(cursor, inserted_id)

    def executemany(self, query, seq_of_params):
        sql = self._normalize_sql(query)
        with self._connection.cursor() as cursor:
            cursor.executemany(sql, seq_of_params)

    def executescript(self, script):
        statements = [item.strip() for item in str(script).split(';') if item.strip()]
        with self._connection.cursor() as cursor:
            for statement in statements:
                cursor.execute(self._normalize_sql(statement))

    def cursor(self):
        return self._connection.cursor(cursor_factory=DictCursor)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        if self._released:
            return
        self._released = True
        if self._release_hook:
            self._release_hook(self._connection)
            return
        self._connection.close()

    def __getattr__(self, name):
        return getattr(self._connection, name)


LegacyPostgresConnectionWrapper = PostgresConnectionWrapper


def get_connection_pool():
    global _CONNECTION_POOL
    if _CONNECTION_POOL:
        return _CONNECTION_POOL
    with _CONNECTION_POOL_LOCK:
        if _CONNECTION_POOL:
            return _CONNECTION_POOL
        if not DB_CONNECTOR_AVAILABLE:
            raise RuntimeError('Instale psycopg2-binary para usar o servidor Postgres/Supabase.')
        if not DATABASE_URL:
            raise RuntimeError('DATABASE_URL nao configurada.')
        _CONNECTION_POOL = psycopg2_pool.SimpleConnectionPool(DB_POOL_MINCONN, DB_POOL_MAXCONN, DATABASE_URL)
        structured_log('info', 'db.pool_initialized', minconn=DB_POOL_MINCONN, maxconn=DB_POOL_MAXCONN)
        return _CONNECTION_POOL


def release_connection(raw_connection):
    pool = get_connection_pool()
    pool.putconn(raw_connection)


def db_pool_status():
    pool = _CONNECTION_POOL
    if not pool:
        return {
            'enabled': DB_CONNECTOR_AVAILABLE and bool(DATABASE_URL),
            'initialized': False,
            'minconn': DB_POOL_MINCONN,
            'maxconn': DB_POOL_MAXCONN,
            'available': 0,
            'in_use': 0
        }
    available = len(getattr(pool, '_pool', []) or [])
    in_use = len(getattr(pool, '_used', {}) or {})
    return {
        'enabled': True,
        'initialized': True,
        'minconn': DB_POOL_MINCONN,
        'maxconn': DB_POOL_MAXCONN,
        'available': int(available),
        'in_use': int(in_use)
    }


def get_connection():
    if not DB_CONNECTOR_AVAILABLE:
        raise RuntimeError('Instale psycopg2-binary para usar o servidor Postgres/Supabase.')
    if not DATABASE_URL:
        raise RuntimeError('DATABASE_URL nao configurada.')
    pool = get_connection_pool()
    raw_connection = pool.getconn()
    return PostgresConnectionWrapper(raw_connection, release_hook=release_connection)


def legacy_get_connection():
    if not DB_CONNECTOR_AVAILABLE:
        raise RuntimeError('Instale psycopg2-binary para usar o servidor Postgres/Supabase.')
    if not DATABASE_URL:
        raise RuntimeError('DATABASE_URL nao configurada.')
    raw_connection = psycopg2.connect(DATABASE_URL)
    return LegacyPostgresConnectionWrapper(raw_connection)
