"""Constantes e mapa de permissões do sistema EPI Controle."""

# --- Permissões individuais ---

PERM_DASHBOARD_VIEW = 'dashboard:view'

PERM_USERS_VIEW = 'users:view'
PERM_USERS_CREATE = 'users:create'
PERM_USERS_UPDATE = 'users:update'
PERM_USERS_DELETE = 'users:delete'

PERM_UNITS_VIEW = 'units:view'
PERM_UNITS_CREATE = 'units:create'
PERM_UNITS_UPDATE = 'units:update'
PERM_UNITS_DELETE = 'units:delete'

PERM_EMPLOYEES_VIEW = 'employees:view'
PERM_EMPLOYEES_CREATE = 'employees:create'
PERM_EMPLOYEES_UPDATE = 'employees:update'
PERM_EMPLOYEES_DELETE = 'employees:delete'

PERM_EPIS_VIEW = 'epis:view'
PERM_EPIS_CREATE = 'epis:create'
PERM_EPIS_UPDATE = 'epis:update'
PERM_EPIS_DELETE = 'epis:delete'

PERM_DELIVERIES_VIEW = 'deliveries:view'
PERM_DELIVERIES_CREATE = 'deliveries:create'

PERM_FICHAS_VIEW = 'fichas:view'
PERM_REPORTS_VIEW = 'reports:view'
PERM_ALERTS_VIEW = 'alerts:view'

PERM_COMPANIES_VIEW = 'companies:view'
PERM_COMPANIES_CREATE = 'companies:create'
PERM_COMPANIES_UPDATE = 'companies:update'
PERM_COMPANIES_LICENSE = 'companies:license'

PERM_COMMERCIAL_VIEW = 'commercial:view'
PERM_USAGE_VIEW = 'usage:view'

PERM_STOCK_VIEW = 'stock:view'
PERM_STOCK_ADJUST = 'stock:adjust'

PERM_SETTINGS_VIEW = 'settings:view'
PERM_SETTINGS_UPDATE = 'settings:update'

PERM_EPI_VIEW_SELF = 'epi:view_self'
PERM_EPI_SIGN = 'epi:sign'

PERM_PURCHASE_REQUESTS_VIEW = 'purchase_requests:view'
PERM_PURCHASE_REQUESTS_CREATE = 'purchase_requests:create'
PERM_PURCHASE_REQUESTS_UPDATE = 'purchase_requests:update'

PERM_PO_VIEW = 'purchase_orders:view'
PERM_PO_CREATE = 'purchase_orders:create'
PERM_PO_UPLOAD = 'purchase_orders:upload'
PERM_PO_APPROVE = 'purchase_orders:approve'
PERM_PO_RECEIVE = 'purchase_orders:receive'
PERM_PO_REVIEW = 'purchase_orders:review'

PERM_FINANCE_VIEW = 'finance:view'
PERM_SUPPLIERS_MANAGE = 'suppliers:manage'
PERM_UNIT_LINKS_MANAGE = 'unit_links:manage'

# Módulo de Compras — cotações (RFQ) e catálogo de fornecedores (Fase F0)
PERM_QUOTES_VIEW = 'quotes:view'
PERM_QUOTES_MANAGE = 'quotes:manage'
PERM_SUPPLIER_CATALOG_VIEW = 'supplier_catalog:view'

PERM_EPI_FEEDBACK_VIEW = 'epi_feedback:view'
PERM_EPI_FEEDBACK_CREATE = 'epi_feedback:create'
PERM_EPI_FEEDBACK_TRIAGE = 'epi_feedback:triage'
PERM_EPI_FEEDBACK_HSEQ_REVIEW = 'epi_feedback:hseq_review'
PERM_EPI_FEEDBACK_ADMIN_APPROVE = 'epi_feedback:admin_approve'
PERM_EPI_FEEDBACK_CLOSE = 'epi_feedback:close'
PERM_EPI_FEEDBACK_MANAGER_EVAL = 'epi_feedback:manager_eval'

PERM_EPI_EVALUATION_VIEW = 'epi_evaluation:view'
PERM_EPI_EVALUATION_DECIDE = 'epi_evaluation:decide'
PERM_EPI_SUGGESTION_ACCEPT = 'epi_evaluation:accept_suggestion'

# --- Grupos de permissões reutilizáveis ---

ADMIN_BASE_PERMISSIONS: frozenset[str] = frozenset({
    PERM_DASHBOARD_VIEW,
    PERM_USERS_VIEW, PERM_USERS_CREATE, PERM_USERS_UPDATE, PERM_USERS_DELETE,
    PERM_UNITS_VIEW, PERM_UNITS_CREATE, PERM_UNITS_UPDATE, PERM_UNITS_DELETE,
    PERM_EMPLOYEES_VIEW, PERM_EMPLOYEES_CREATE, PERM_EMPLOYEES_UPDATE, PERM_EMPLOYEES_DELETE,
    PERM_EPIS_VIEW, PERM_EPIS_CREATE, PERM_EPIS_UPDATE, PERM_EPIS_DELETE,
    PERM_DELIVERIES_VIEW, PERM_FICHAS_VIEW, PERM_REPORTS_VIEW, PERM_ALERTS_VIEW, PERM_STOCK_VIEW,
})

DELIVERY_WRITE_PERMISSIONS: frozenset[str] = frozenset({PERM_DELIVERIES_CREATE})
COMPANY_CORE_PERMISSIONS: frozenset[str] = frozenset({PERM_COMPANIES_VIEW})
COMPANY_MANAGEMENT_PERMISSIONS: frozenset[str] = frozenset({
    PERM_COMPANIES_CREATE, PERM_COMPANIES_UPDATE, PERM_COMPANIES_LICENSE,
})
COMMERCIAL_PERMISSIONS: frozenset[str] = frozenset({PERM_COMMERCIAL_VIEW, PERM_USAGE_VIEW})
STOCK_MANAGEMENT_PERMISSIONS: frozenset[str] = frozenset({PERM_STOCK_ADJUST})

PURCHASE_VIEW_PERMISSIONS: frozenset[str] = frozenset({
    PERM_PURCHASE_REQUESTS_VIEW, PERM_PO_VIEW, PERM_FINANCE_VIEW,
    PERM_QUOTES_VIEW, PERM_SUPPLIER_CATALOG_VIEW,
})
PURCHASE_BUYER_PERMISSIONS: frozenset[str] = frozenset({
    PERM_PURCHASE_REQUESTS_VIEW, PERM_PURCHASE_REQUESTS_UPDATE,
    PERM_PO_VIEW, PERM_PO_CREATE, PERM_PO_UPLOAD, PERM_FINANCE_VIEW,
    PERM_QUOTES_VIEW, PERM_QUOTES_MANAGE, PERM_SUPPLIER_CATALOG_VIEW,
})
PURCHASE_APPROVER_PERMISSIONS: frozenset[str] = frozenset({
    PERM_PURCHASE_REQUESTS_VIEW, PERM_PO_VIEW, PERM_PO_APPROVE, PERM_FINANCE_VIEW,
    PERM_QUOTES_VIEW, PERM_SUPPLIER_CATALOG_VIEW,
})
PURCHASE_ADMIN_PERMISSIONS: frozenset[str] = frozenset({
    PERM_PURCHASE_REQUESTS_VIEW, PERM_PURCHASE_REQUESTS_CREATE, PERM_PURCHASE_REQUESTS_UPDATE,
    PERM_PO_VIEW, PERM_PO_REVIEW, PERM_PO_RECEIVE, PERM_FINANCE_VIEW,
    PERM_QUOTES_VIEW, PERM_SUPPLIER_CATALOG_VIEW,
})

EPI_FEEDBACK_MANAGER_PERMISSIONS: frozenset[str] = frozenset({
    PERM_EPI_FEEDBACK_VIEW, PERM_EPI_FEEDBACK_TRIAGE,
})
EPI_FEEDBACK_ADMIN_PERMISSIONS: frozenset[str] = frozenset({
    PERM_EPI_FEEDBACK_VIEW, PERM_EPI_FEEDBACK_ADMIN_APPROVE, PERM_EPI_FEEDBACK_CLOSE,
})

# --- Mapa final de permissões por role ---

PERMISSIONS: dict[str, frozenset[str]] = {
    'master_admin': (
        ADMIN_BASE_PERMISSIONS | DELIVERY_WRITE_PERMISSIONS | COMPANY_CORE_PERMISSIONS
        | COMPANY_MANAGEMENT_PERMISSIONS | COMMERCIAL_PERMISSIONS | STOCK_MANAGEMENT_PERMISSIONS
        | PURCHASE_VIEW_PERMISSIONS | PURCHASE_BUYER_PERMISSIONS | PURCHASE_APPROVER_PERMISSIONS
        | PURCHASE_ADMIN_PERMISSIONS | EPI_FEEDBACK_MANAGER_PERMISSIONS | EPI_FEEDBACK_ADMIN_PERMISSIONS
        | frozenset({
            PERM_PURCHASE_REQUESTS_CREATE, PERM_SETTINGS_VIEW, PERM_SETTINGS_UPDATE,
            PERM_SUPPLIERS_MANAGE, PERM_UNIT_LINKS_MANAGE,
            PERM_EPI_FEEDBACK_HSEQ_REVIEW, PERM_EPI_FEEDBACK_CREATE,
        })
    ),
    'general_admin': (
        ADMIN_BASE_PERMISSIONS | DELIVERY_WRITE_PERMISSIONS | COMPANY_CORE_PERMISSIONS
        | STOCK_MANAGEMENT_PERMISSIONS | PURCHASE_VIEW_PERMISSIONS | PURCHASE_BUYER_PERMISSIONS
        | PURCHASE_APPROVER_PERMISSIONS | PURCHASE_ADMIN_PERMISSIONS
        | EPI_FEEDBACK_MANAGER_PERMISSIONS | EPI_FEEDBACK_ADMIN_PERMISSIONS
        | frozenset({
            PERM_PURCHASE_REQUESTS_CREATE, PERM_SETTINGS_VIEW, PERM_SETTINGS_UPDATE,
            PERM_SUPPLIERS_MANAGE, PERM_UNIT_LINKS_MANAGE,
            PERM_EPI_FEEDBACK_HSEQ_REVIEW, PERM_EPI_FEEDBACK_CREATE,
            PERM_EPI_FEEDBACK_MANAGER_EVAL,
            PERM_EPI_EVALUATION_VIEW, PERM_EPI_EVALUATION_DECIDE, PERM_EPI_SUGGESTION_ACCEPT,
        })
    ),
    'registry_admin': (
        ADMIN_BASE_PERMISSIONS | PURCHASE_VIEW_PERMISSIONS | PURCHASE_ADMIN_PERMISSIONS
        | EPI_FEEDBACK_ADMIN_PERMISSIONS
        | frozenset({
            PERM_PURCHASE_REQUESTS_CREATE, PERM_SETTINGS_VIEW, PERM_SETTINGS_UPDATE,
            PERM_UNIT_LINKS_MANAGE,
            PERM_EPI_FEEDBACK_CREATE, PERM_EPI_FEEDBACK_TRIAGE, PERM_EPI_FEEDBACK_MANAGER_EVAL,
            PERM_EPI_EVALUATION_VIEW, PERM_EPI_EVALUATION_DECIDE,
        })
    ),
    'admin': (
        frozenset({
            PERM_DASHBOARD_VIEW, PERM_USERS_VIEW, PERM_UNITS_VIEW,
            PERM_EMPLOYEES_VIEW, PERM_EMPLOYEES_UPDATE,
            PERM_EPIS_VIEW, PERM_DELIVERIES_VIEW, PERM_FICHAS_VIEW,
            PERM_REPORTS_VIEW, PERM_ALERTS_VIEW, PERM_STOCK_VIEW,
        })
        | DELIVERY_WRITE_PERMISSIONS | STOCK_MANAGEMENT_PERMISSIONS | PURCHASE_ADMIN_PERMISSIONS
        | frozenset({
            PERM_EPI_FEEDBACK_VIEW, PERM_EPI_FEEDBACK_CREATE, PERM_EPI_EVALUATION_VIEW,
        })
    ),
    'buyer': (
        frozenset({
            PERM_DASHBOARD_VIEW, PERM_EPIS_VIEW, PERM_UNITS_VIEW,
            PERM_STOCK_VIEW, PERM_DELIVERIES_VIEW,
        })
        | PURCHASE_BUYER_PERMISSIONS
    ),
    'approver': (
        frozenset({
            PERM_DASHBOARD_VIEW, PERM_EPIS_VIEW, PERM_UNITS_VIEW,
            PERM_STOCK_VIEW, PERM_DELIVERIES_VIEW,
        })
        | PURCHASE_APPROVER_PERMISSIONS
    ),
    'user': (
        frozenset({
            PERM_DASHBOARD_VIEW, PERM_DELIVERIES_VIEW, PERM_FICHAS_VIEW,
            PERM_ALERTS_VIEW, PERM_UNITS_VIEW, PERM_EMPLOYEES_VIEW,
            PERM_EPIS_VIEW, PERM_STOCK_VIEW,
        })
        | DELIVERY_WRITE_PERMISSIONS | STOCK_MANAGEMENT_PERMISSIONS
        | frozenset({
            PERM_EPI_FEEDBACK_VIEW, PERM_EPI_FEEDBACK_TRIAGE,
            PERM_EPI_FEEDBACK_MANAGER_EVAL, PERM_EPI_EVALUATION_VIEW,
        })
    ),
    'epi_manager': (
        frozenset({
            PERM_DASHBOARD_VIEW, PERM_DELIVERIES_VIEW, PERM_FICHAS_VIEW,
            PERM_ALERTS_VIEW, PERM_UNITS_VIEW, PERM_EMPLOYEES_VIEW,
            PERM_EPIS_VIEW, PERM_STOCK_VIEW,
        })
        | EPI_FEEDBACK_MANAGER_PERMISSIONS
        | frozenset({PERM_EPI_FEEDBACK_HSEQ_REVIEW, PERM_EPI_FEEDBACK_CREATE})
    ),
    'employee': frozenset({PERM_EPI_VIEW_SELF, PERM_EPI_SIGN}),
}
