-- Migration: tenant_domains (domínios por tenant com verificação CNAME/SSL)
--            + colunas de 2FA (TOTP) para o primeiro acesso do Owner.
-- Idempotente: IF NOT EXISTS em tabela, índices e colunas; backfill com NOT EXISTS.

CREATE TABLE IF NOT EXISTS tenant_domains (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    domain TEXT NOT NULL,
    domain_type TEXT NOT NULL DEFAULT 'custom_domain',
    verification_token TEXT NOT NULL DEFAULT '',
    verification_status TEXT NOT NULL DEFAULT 'pending',
    ssl_status TEXT NOT NULL DEFAULT 'pending',
    is_primary INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT '',
    verified_at TEXT NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tenant_domains_domain
  ON tenant_domains (domain_type, domain);
CREATE INDEX IF NOT EXISTS idx_tenant_domains_company
  ON tenant_domains (company_id);

-- Backfill dos campos legados de roteamento (já em uso → verificados)
INSERT INTO tenant_domains (company_id, domain, domain_type, verification_status, ssl_status, is_primary, created_at, verified_at)
SELECT c.id, c.subdomain, 'platform_subdomain', 'verified', 'active', 1,
       COALESCE(c.contract_start, ''), COALESCE(c.contract_start, '')
FROM companies c
WHERE c.subdomain IS NOT NULL AND c.subdomain != ''
  AND NOT EXISTS (
    SELECT 1 FROM tenant_domains td
    WHERE td.domain_type = 'platform_subdomain' AND td.domain = c.subdomain
  );

INSERT INTO tenant_domains (company_id, domain, domain_type, verification_status, ssl_status, is_primary, created_at, verified_at)
SELECT c.id, c.custom_domain, 'custom_domain', 'verified', 'active', 0,
       COALESCE(c.contract_start, ''), COALESCE(c.contract_start, '')
FROM companies c
WHERE c.custom_domain IS NOT NULL AND c.custom_domain != ''
  AND NOT EXISTS (
    SELECT 1 FROM tenant_domains td
    WHERE td.domain_type = 'custom_domain' AND td.domain = c.custom_domain
  );

-- 2FA (TOTP) por usuário
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS totp_secret TEXT,
  ADD COLUMN IF NOT EXISTS totp_enabled INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS terms_accepted_at TEXT;

-- RLS coerente com as demais tabelas por tenant: o acesso é sempre pelo
-- backend (service key); clientes anon/authenticated não acessam direto.
ALTER TABLE tenant_domains ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS block_direct_api_access ON tenant_domains;
CREATE POLICY block_direct_api_access ON tenant_domains
  AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false);
