-- Migration: auditoria do percentual de atenção CORPORATIVO (#271-B1b).
--
-- POR QUE UMA TABELA PRÓPRIA
--
-- A migration 026 criou `unit_epi_stock_config_audit_logs` para os parâmetros
-- por Unidade + EPI. Ela tem `unit_id` e `epi_id` NOT NULL: uma alteração de
-- nível empresa só caberia lá com sentinelas `0`, que seriam mentira (não
-- existe Unidade 0) e ainda apareceriam em toda consulta filtrada por Unidade.
-- Separar preserva a mesma regra das outras três tabelas da #271: o ESCOPO da
-- configuração é a identidade da linha, não uma coluna anulável.
--
-- POR QUE A TABELA NASCEU FORA DE MIGRATION — e por que isto é uma correção
--
-- A tabela entrou apenas em `core/schema.py`. Como o `executescript` também
-- roda contra PostgreSQL, ela passou a existir no schema `public` SEM RLS e
-- SEM a policy `block_direct_api_access`. O schema `public` é exposto pelo
-- PostgREST: uma trilha de auditoria com nome do ator, IP e user agent de todo
-- tenant ficaria legível com a chave anon. O guarda de cobertura de RLS
-- (`tests_postgres/test_rls_coverage_postgres.py`, issue #205) pegou isso no
-- próprio PR — que é exatamente para o que ele foi escrito.
--
-- Aditiva e não-destrutiva. RLS habilitada já nesta migration.

CREATE TABLE IF NOT EXISTS company_stock_attention_config_audit_logs (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          INTEGER NOT NULL,
    -- 'set' (gravou um percentual corporativo) ou 'restore_default' (apagou a
    -- linha e devolveu a empresa ao padrão do sistema). Salvar 20% e restaurar
    -- o padrão de 20% resultam no mesmo número e em origens opostas; sem
    -- `action`, a trilha não distinguiria as duas decisões.
    action              TEXT NOT NULL DEFAULT 'set',
    -- NULL significa "não havia configuração corporativa" — distinto de 0, que
    -- é percentual válido e configurado.
    previous_percentage INTEGER,
    new_percentage      INTEGER NOT NULL,
    previous_source     TEXT NOT NULL DEFAULT '',
    new_source          TEXT NOT NULL DEFAULT '',
    actor_user_id       INTEGER,
    actor_name          TEXT NOT NULL DEFAULT '',
    actor_role          TEXT NOT NULL DEFAULT '',
    ip_address          TEXT NOT NULL DEFAULT '',
    user_agent          TEXT NOT NULL DEFAULT '',
    created_at          TEXT NOT NULL,
    FOREIGN KEY (company_id)    REFERENCES companies (id) ON DELETE CASCADE,
    FOREIGN KEY (actor_user_id) REFERENCES users (id)     ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_company_stock_attention_audit_scope
    ON company_stock_attention_config_audit_logs (company_id, created_at);

-- RLS: mesma policy restritiva do resto do backend. O backend Python (role
-- postgres) não é afetado.
DO $$
DECLARE
  tbl text := 'company_stock_attention_config_audit_logs';
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = tbl
  ) THEN
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public' AND tablename = tbl
        AND policyname = 'block_direct_api_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY block_direct_api_access ON public.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false)',
        tbl
      );
    END IF;
  END IF;
END $$;
