-- Migration: faixa de atenção e habilitação de alerta por Unidade + EPI (#271).
--
-- A fatia 1.1D-B0 criou o mínimo por Unidade. Faltavam dois parâmetros para o
-- sistema conseguir dizer o que o operador precisa saber:
--
--   1. uma FAIXA DE ATENÇÃO acima do mínimo (laranja), para avisar antes de o
--      estoque ficar crítico e não só quando já está;
--   2. um LIGA/DESLIGA do monitoramento por Unidade + EPI, porque uma Unidade
--      pode ter saldo residual de um EPI que não usa mais operacionalmente — e
--      manter alerta vermelho permanente sobre isso treina o operador a ignorar
--      alertas, que é pior do que não ter alerta.
--
-- TRÊS TABELAS, TRÊS PARÂMETROS INDEPENDENTES
--
-- Mínimo, percentual e habilitação são configurações separadas: alterar uma
-- nunca pode tocar as outras. Numa tabela só, todo UPSERT precisaria preservar
-- os campos vizinhos, e o primeiro esquecimento zeraria um parâmetro em
-- silêncio. Separadas, isso é impossível por construção.
--
-- A separação também preserva a regra que vale nas três: **a existência da
-- linha É a configuração local**. Numa tabela compartilhada, "linha existe"
-- passaria a significar "percentual configurado OU alerta configurado OU
-- ambos", e a distinção teria de migrar para colunas anuláveis — trocando o
-- critério que já vale em `unit_epi_minimum_stock`.
--
-- SEM BACKFILL, como na B0. Linha criada em massa marcaria como
-- `unit_configured` quem nunca configurou nada, fabricando decisões que
-- ninguém tomou. A ausência resolve para o padrão e diz a verdade.
--
-- HERANÇA — e uma assimetria deliberada
--
--   mínimo      : epis.minimum_stock (empresa)            -> unit_configured
--   percentual  : company_stock_attention_config (empresa) -> unit_configured
--   alerta      : constante do sistema (true)              -> unit_configured
--
-- Para mínimo e percentual a origem herdada é `company_default`: existe mesmo
-- uma configuração da empresa por trás. Para o alerta ela é `system_default`,
-- porque hoje NÃO existe liga/desliga corporativo — chamar a constante de
-- "padrão da empresa" afirmaria uma decisão administrativa que nunca foi
-- tomada. Se um dia houver toggle corporativo, entra um degrau no meio
-- (`system_default -> company_default -> unit_configured`) sem que nenhum
-- consumidor precise mudar.
--
-- Aditiva e não-destrutiva. RLS habilitada já nesta migration.

-- ── Padrão da empresa para a faixa de atenção ────────────────────────────────
-- Em tabela, e não como constante no código, para que o Administrador Geral
-- possa mudar o padrão sem deploy.
CREATE TABLE IF NOT EXISTS company_stock_attention_config (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL UNIQUE,
    attention_percentage INTEGER NOT NULL DEFAULT 20,
    updated_by_user_id   INTEGER,
    created_at           TEXT NOT NULL DEFAULT '',
    updated_at           TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    FOREIGN KEY (updated_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

-- ── Faixa de atenção personalizada por Unidade + EPI ─────────────────────────
CREATE TABLE IF NOT EXISTS unit_epi_attention_percentage (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    unit_id              INTEGER NOT NULL,
    epi_id               INTEGER NOT NULL,
    -- Zero é configuração VÁLIDA: significa "sem faixa de atenção, me avise só
    -- no crítico". Por isso a resolução testa a EXISTÊNCIA da linha, nunca a
    -- truthiness do valor.
    attention_percentage INTEGER NOT NULL DEFAULT 0,
    created_by_user_id   INTEGER,
    updated_by_user_id   INTEGER,
    created_at           TEXT NOT NULL DEFAULT '',
    updated_at           TEXT NOT NULL DEFAULT '',
    UNIQUE (company_id, unit_id, epi_id),
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    FOREIGN KEY (unit_id)    REFERENCES units (id)     ON DELETE CASCADE,
    FOREIGN KEY (epi_id)     REFERENCES epis (id)      ON DELETE CASCADE,
    FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

-- ── Habilitação do monitoramento por Unidade + EPI ───────────────────────────
--
-- TRÊS estados persistidos, e o terceiro é o que exige cuidado:
--
--   sem linha              -> habilitado, alert_source = 'system_default'
--   linha alert_enabled=0  -> desabilitado, alert_source = 'unit_configured'
--   linha alert_enabled=1  -> habilitado,   alert_source = 'unit_configured'
--
-- Reativar GRAVA 1; não apaga a linha. Apagar tornaria o EPI indistinguível de
-- um que nunca foi tocado, perdendo exatamente o que `source` existe para
-- preservar — a mesma razão pela qual, na B0, mínimo 100 herdado e mínimo 100
-- configurado são estados diferentes com o mesmo número.
CREATE TABLE IF NOT EXISTS unit_epi_stock_alert_settings (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,
    unit_id            INTEGER NOT NULL,
    epi_id             INTEGER NOT NULL,
    alert_enabled      INTEGER NOT NULL DEFAULT 1,
    created_by_user_id INTEGER,
    updated_by_user_id INTEGER,
    created_at         TEXT NOT NULL DEFAULT '',
    updated_at         TEXT NOT NULL DEFAULT '',
    UNIQUE (company_id, unit_id, epi_id),
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    FOREIGN KEY (unit_id)    REFERENCES units (id)     ON DELETE CASCADE,
    FOREIGN KEY (epi_id)     REFERENCES epis (id)      ON DELETE CASCADE,
    FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

-- ── Auditoria dos dois parâmetros novos ──────────────────────────────────────
--
-- `parameter` discrimina qual configuração mudou. O mínimo continua em
-- `unit_epi_minimum_stock_audit_logs` (fatia 1.1D-B0): consolidar exigiria
-- migrar linhas de auditoria já gravadas, e mexer em trilha de auditoria por
-- simetria de nome não compensa.
--
-- Valores como TEXT porque a tabela cobre parâmetros de tipos diferentes
-- (percentual inteiro, habilitação booleana). `previous_value` NULL significa
-- "não havia configuração local" — distinto de '0' e de 'false', que são
-- valores configurados.
CREATE TABLE IF NOT EXISTS unit_epi_stock_config_audit_logs (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id      INTEGER NOT NULL,
    unit_id         INTEGER NOT NULL,
    epi_id          INTEGER NOT NULL,
    parameter       TEXT NOT NULL,
    previous_value  TEXT,
    new_value       TEXT NOT NULL,
    previous_source TEXT NOT NULL DEFAULT '',
    actor_user_id   INTEGER,
    actor_name      TEXT NOT NULL DEFAULT '',
    actor_role      TEXT NOT NULL DEFAULT '',
    ip_address      TEXT NOT NULL DEFAULT '',
    user_agent      TEXT NOT NULL DEFAULT '',
    created_at      TEXT NOT NULL,
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    FOREIGN KEY (unit_id)    REFERENCES units (id)     ON DELETE CASCADE,
    FOREIGN KEY (epi_id)     REFERENCES epis (id)      ON DELETE CASCADE,
    FOREIGN KEY (actor_user_id) REFERENCES users (id)  ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_unit_epi_attention_unit
    ON unit_epi_attention_percentage (company_id, unit_id);

CREATE INDEX IF NOT EXISTS idx_unit_epi_alert_settings_unit
    ON unit_epi_stock_alert_settings (company_id, unit_id);

CREATE INDEX IF NOT EXISTS idx_unit_epi_stock_config_audit_scope
    ON unit_epi_stock_config_audit_logs (company_id, unit_id, epi_id, parameter, created_at);

-- RLS: mesma policy restritiva do resto do backend. O schema public é exposto
-- pelo PostgREST — sem isto, o parâmetro de estoque de todo tenant seria
-- legível com a chave anon. O backend Python (role postgres) não é afetado.
DO $$
DECLARE
  tbl text := 'company_stock_attention_config';
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = tbl
  ) THEN
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public' AND tablename = tbl
        AND policyname = 'block_direct_api_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY block_direct_api_access ON public.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false)',
        tbl
      );
    END IF;
  END IF;
END $$;

DO $$
DECLARE
  tbl text := 'unit_epi_attention_percentage';
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = tbl
  ) THEN
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public' AND tablename = tbl
        AND policyname = 'block_direct_api_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY block_direct_api_access ON public.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false)',
        tbl
      );
    END IF;
  END IF;
END $$;

DO $$
DECLARE
  tbl text := 'unit_epi_stock_alert_settings';
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = tbl
  ) THEN
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public' AND tablename = tbl
        AND policyname = 'block_direct_api_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY block_direct_api_access ON public.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false)',
        tbl
      );
    END IF;
  END IF;
END $$;

DO $$
DECLARE
  tbl text := 'unit_epi_stock_config_audit_logs';
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = tbl
  ) THEN
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public' AND tablename = tbl
        AND policyname = 'block_direct_api_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY block_direct_api_access ON public.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false)',
        tbl
      );
    END IF;
  END IF;
END $$;
