-- Migration: Arquitetura Multi-CNPJ / Joint Venture (LegalEntity)
--
-- Cada empresa contratante (tenant, tabela companies) passa a poder possuir um
-- ou vários CNPJs (matriz, filiais, subsidiárias, SPEs, empresas sócias de
-- Joint Venture). O modelo preserva a arquitetura SaaS Multi-Tenant existente:
-- companies continua sendo a fronteira de faturamento/assinatura; legal_entities
-- é a nova fronteira jurídica/fiscal/trabalhista abaixo dela.
--
-- Idempotente e não-destrutiva: colunas de vínculo são nullable e recebem
-- backfill para a matriz padrão de cada empresa. Nenhum dado é perdido.

CREATE TABLE IF NOT EXISTS legal_entities (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             INTEGER NOT NULL,
    cnpj                   TEXT NOT NULL,
    legal_name             TEXT NOT NULL DEFAULT '',
    trade_name             TEXT NOT NULL DEFAULT '',
    entity_type            TEXT NOT NULL DEFAULT 'matriz',
    parent_entity_id       INTEGER,
    state_registration     TEXT NOT NULL DEFAULT '',
    municipal_registration TEXT NOT NULL DEFAULT '',
    cnae                   TEXT NOT NULL DEFAULT '',
    address                TEXT NOT NULL DEFAULT '',
    municipality           TEXT NOT NULL DEFAULT '',
    uf                     TEXT NOT NULL DEFAULT '',
    cep                    TEXT NOT NULL DEFAULT '',
    opening_date           TEXT NOT NULL DEFAULT '',
    registration_status    TEXT NOT NULL DEFAULT 'ativa',
    is_headquarters        INTEGER NOT NULL DEFAULT 1,
    active                 INTEGER NOT NULL DEFAULT 1,
    notes                  TEXT NOT NULL DEFAULT '',
    created_at             TEXT NOT NULL DEFAULT '',
    updated_at             TEXT NOT NULL DEFAULT '',
    UNIQUE (company_id, cnpj),
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    FOREIGN KEY (parent_entity_id) REFERENCES legal_entities (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_legal_entities_company ON legal_entities (company_id, active);

-- Estrutura organizacional escolhida no onboarding + granularidade de estoque.
ALTER TABLE companies
  ADD COLUMN IF NOT EXISTS org_structure_type  TEXT NOT NULL DEFAULT 'single_cnpj',
  ADD COLUMN IF NOT EXISTS stock_control_scope TEXT NOT NULL DEFAULT 'company';

-- Vínculo do colaborador e da unidade ao CNPJ (nullable => retrocompatível).
ALTER TABLE employees ADD COLUMN IF NOT EXISTS legal_entity_id INTEGER;
ALTER TABLE units     ADD COLUMN IF NOT EXISTS legal_entity_id INTEGER;

CREATE INDEX IF NOT EXISTS idx_employees_legal_entity ON employees (legal_entity_id);
CREATE INDEX IF NOT EXISTS idx_units_legal_entity ON units (legal_entity_id);

-- Backfill: matriz padrão por empresa a partir do CNPJ/razão social atual.
INSERT INTO legal_entities (company_id, cnpj, legal_name, trade_name, entity_type,
                            is_headquarters, active, created_at, updated_at)
SELECT c.id,
       COALESCE(c.cnpj, ''),
       COALESCE(NULLIF(c.legal_name, ''), c.name),
       COALESCE(c.name, ''),
       'matriz', 1, 1,
       to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
       to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS')
FROM companies c
WHERE NOT EXISTS (
    SELECT 1 FROM legal_entities le WHERE le.company_id = c.id
);

-- Revincula colaboradores e unidades órfãos à matriz padrão da sua empresa.
UPDATE employees e
SET legal_entity_id = (
    SELECT le.id FROM legal_entities le
    WHERE le.company_id = e.company_id
    ORDER BY le.id LIMIT 1
)
WHERE e.legal_entity_id IS NULL;

UPDATE units u
SET legal_entity_id = (
    SELECT le.id FROM legal_entities le
    WHERE le.company_id = u.company_id
    ORDER BY le.id LIMIT 1
)
WHERE u.legal_entity_id IS NULL;
