-- Migration: vínculo local do colaborador terceirizado com a Unidade
-- (ADR-0002 §13, PR B da issue #180).
--
-- Permite reutilizar a MESMA pessoa em mais de uma Unidade sem duplicar o
-- cadastro: `employees` continua sendo a única fonte de identidade no
-- tenant, e esta tabela guarda só o vínculo — nunca uma cópia de dado
-- pessoal.
--
-- Estrutura PARALELA e INDEPENDENTE de `employees.unit_id`. Não a
-- substitui, não a torna imutável (proposta explicitamente REJEITADA na
-- rodada 2 da issue #180) e não toca a transferência definitiva nem a
-- movimentação temporária (`employee_unit_movements`).
--
-- O vínculo local NÃO autoriza entrega de EPI: o gate continua decidindo
-- apenas pela Unidade atual de movimentação (ADR-0002 §13.17, pergunta 1).
-- Serve para listagem, seleção e arquivamento por Unidade.
--
-- Sem as colunas de contrato de `outsourced_company_unit_links`: o contrato
-- é da EMPRESA com a Unidade e já vive lá. Repeti-lo por pessoa criaria uma
-- segunda verdade sobre o mesmo contrato.
--
-- Idempotente e não-destrutiva: uma tabela nova, nenhuma coluna existente
-- removida ou alterada. RLS habilitado já nesta migration.

CREATE TABLE IF NOT EXISTS employee_unit_links (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             INTEGER NOT NULL,
    employee_id            INTEGER NOT NULL,
    unit_id                INTEGER NOT NULL,
    local_status           TEXT NOT NULL DEFAULT 'active',
    notes                  TEXT NOT NULL DEFAULT '',
    activated_at           TEXT NOT NULL DEFAULT '',
    deactivated_at         TEXT,
    deactivated_by_user_id INTEGER,
    deactivation_reason    TEXT NOT NULL DEFAULT '',
    created_by_user_id     INTEGER,
    updated_by_user_id     INTEGER,
    created_at             TEXT NOT NULL DEFAULT '',
    updated_at             TEXT NOT NULL DEFAULT '',
    -- Mesma proteção do molde contra duas Unidades vinculando a mesma
    -- pessoa quase ao mesmo tempo (ADR-0002 §13.4).
    UNIQUE (company_id, employee_id, unit_id),
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE,
    FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE CASCADE,
    FOREIGN KEY (deactivated_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_employee_unit_links_unit
    ON employee_unit_links (unit_id, local_status);

-- RLS: mesma policy restritiva de todo o resto do backend. O schema public
-- é exposto pelo PostgREST — sem isto, a tabela seria legível com a chave
-- anon. O backend Python (role postgres) não é afetado.
DO $$
DECLARE
  tbl text := 'employee_unit_links';
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = tbl
  ) THEN
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);

    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = tbl
        AND policyname = 'block_direct_api_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY block_direct_api_access ON public.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false)',
        tbl
      );
    END IF;
  END IF;
END $$;

-- Backfill: quem é mão de obra CONTRATADA ganha o vínculo na Unidade onde
-- já estava. Identificação por `outsourced_company_id` (vínculo estruturado
-- do ADR-0002) OU por `empresa_origem` não vazia (o campo legado, única
-- identificação disponível para quem veio de importação).
--
-- Mão de obra própria fica de fora: o normalizador força `empresa_origem`
-- vazia para CLT, aprendiz, praticante e estagiário, então o predicado não
-- os alcança — e não deveria, porque o vínculo local existe para resolver
-- reuso de terceirizado entre Unidades.
--
-- Só a Unidade de cadastro. Não pré-popula as demais: cada Unidade povoa a
-- sua deliberadamente (D9/D10), e herdar a lista inteira é exatamente o que
-- o §13.6 proíbe.
INSERT INTO employee_unit_links
    (company_id, employee_id, unit_id, local_status, notes, activated_at, created_at, updated_at)
SELECT e.company_id, e.id, e.unit_id, 'active',
       'Vínculo criado automaticamente a partir da Unidade de cadastro.',
       to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
       to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
       to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS')
FROM employees e
WHERE e.unit_id IS NOT NULL
  AND (
        (e.outsourced_company_id IS NOT NULL AND e.outsourced_company_id <> 0)
     OR (e.empresa_origem IS NOT NULL AND e.empresa_origem <> '')
  )
  AND NOT EXISTS (
    SELECT 1 FROM employee_unit_links l
    WHERE l.company_id = e.company_id
      AND l.employee_id = e.id
      AND l.unit_id = e.unit_id
  );
