-- Migration: escopo de CNPJ por usuário + CNPJ na auditoria (Multi-CNPJ)
--
-- 1) user_legal_entities — autorização explícita de CNPJs para o Administrador
--    Local. Regra de escopo aplicada no backend:
--      • master_admin / general_admin / registry_admin → todos os CNPJs da empresa;
--      • admin (Administrador Local) → apenas os CNPJs autorizados aqui;
--        LISTA VAZIA = sem restrição, para não quebrar usuários já existentes;
--      • user → apenas o CNPJ do colaborador vinculado (derivado, não gravado).
--
-- 2) company_audit_logs.legal_entity_id — o CNPJ afetado pela ação auditada.
--    NULL = ação no nível da empresa (comportamento histórico).

CREATE TABLE IF NOT EXISTS user_legal_entities (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL,
    legal_entity_id INTEGER NOT NULL,
    company_id      INTEGER NOT NULL,
    created_at      TEXT NOT NULL DEFAULT '',
    UNIQUE (user_id, legal_entity_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (legal_entity_id) REFERENCES legal_entities (id) ON DELETE CASCADE,
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_legal_entities_user ON user_legal_entities (user_id);

ALTER TABLE company_audit_logs ADD COLUMN IF NOT EXISTS legal_entity_id INTEGER;
