-- Migration: histórico de vínculo jurídico do colaborador (Multi-CNPJ)
--
-- O CNPJ representa o vínculo jurídico do contrato de trabalho e é IMUTÁVEL
-- após a admissão. A unidade representa apenas a lotação operacional e continua
-- alterável pelos fluxos de transferência já existentes — a transferência de
-- unidade NUNCA altera o CNPJ.
--
-- Mudanças de CNPJ ocorrem somente por processo administrativo específico
-- (POST /api/employees/{id}/legal-entity-transfer), com justificativa
-- obrigatória e auditoria completa. Cada mudança é registrada aqui, preservando
-- o histórico trabalhista/previdenciário do colaborador.

CREATE TABLE IF NOT EXISTS employee_legal_entity_movements (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id            INTEGER NOT NULL,
    company_id             INTEGER NOT NULL,
    source_legal_entity_id INTEGER,
    target_legal_entity_id INTEGER NOT NULL,
    reason                 TEXT NOT NULL DEFAULT '',
    effective_date         TEXT NOT NULL DEFAULT '',
    actor_user_id          INTEGER NOT NULL,
    actor_name             TEXT NOT NULL DEFAULT '',
    created_at             TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (employee_id) REFERENCES employees (id) ON DELETE CASCADE,
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_employee_legal_entity_movements_employee
    ON employee_legal_entity_movements (employee_id);
