-- Migration: Cadastro corporativo compartilhado por tenant + trava
-- pós-promoção de Empresa Terceirizada/Prestadora (ADR-0002 §11).
--
-- outsourced_companies.unit_id deixa de limitar quem enxerga/usa o
-- registro corporativo — vira só "Unidade de origem" (metadado histórico
-- de quem cadastrou primeiro, imutável após a criação; a coluna em si não
-- muda, só o comportamento no backend). Qualquer Unidade do tenant pode
-- localizar o cadastro corporativo já existente (por CNPJ ou nome) e criar
-- seu próprio vínculo em outsourced_company_unit_links (ação "Vincular à
-- minha unidade"), sem duplicar a empresa e sem herdar vínculo, contratos
-- ou colaboradores de outra Unidade.
--
-- outsourced_company_update_requests cobre "Solicitar atualização
-- cadastral": depois que a empresa é promovida ao Cadastro Padrão
-- (registration_mode = 'standard'), editar os dados corporativos passa a
-- ser exclusivo de Administrador Geral/de Registro — Administrador
-- Local/Gestor de EPI registram aqui um pedido para revisão humana, nunca
-- uma edição automática.
--
-- Idempotente e não-destrutiva: duas tabelas novas, nenhuma coluna
-- existente é removida ou perde significado. RLS habilitado já nesta
-- migration (não retroativamente, diferente das tabelas hardened na fase
-- 5) — mesma policy restritiva das demais tabelas do backend.

CREATE TABLE IF NOT EXISTS outsourced_company_unit_links (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             INTEGER NOT NULL,
    outsourced_company_id  INTEGER NOT NULL,
    unit_id                INTEGER NOT NULL,
    local_status           TEXT NOT NULL DEFAULT 'active',
    contract_number        TEXT NOT NULL DEFAULT '',
    contract_start_date    TEXT NOT NULL DEFAULT '',
    contract_end_date      TEXT NOT NULL DEFAULT '',
    local_responsible_id   INTEGER,
    cost_center_ref        TEXT NOT NULL DEFAULT '',
    notes                  TEXT NOT NULL DEFAULT '',
    activated_at           TEXT NOT NULL DEFAULT '',
    deactivated_at         TEXT,
    deactivated_by_user_id INTEGER,
    deactivation_reason    TEXT NOT NULL DEFAULT '',
    created_by_user_id     INTEGER,
    updated_by_user_id     INTEGER,
    created_at             TEXT NOT NULL DEFAULT '',
    updated_at             TEXT NOT NULL DEFAULT '',
    UNIQUE (company_id, outsourced_company_id, unit_id),
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    FOREIGN KEY (outsourced_company_id) REFERENCES outsourced_companies (id) ON DELETE CASCADE,
    FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE CASCADE,
    FOREIGN KEY (local_responsible_id) REFERENCES employees (id) ON DELETE SET NULL,
    FOREIGN KEY (deactivated_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_outsourced_company_unit_links_unit
    ON outsourced_company_unit_links (unit_id, local_status);

CREATE TABLE IF NOT EXISTS outsourced_company_update_requests (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           INTEGER NOT NULL,
    outsourced_company_id INTEGER NOT NULL,
    unit_id              INTEGER,
    requested_by_user_id INTEGER,
    requested_by_name    TEXT NOT NULL DEFAULT '',
    message              TEXT NOT NULL DEFAULT '',
    status                TEXT NOT NULL DEFAULT 'pending',
    resolved_by_user_id  INTEGER,
    resolved_at          TEXT,
    resolution_notes     TEXT NOT NULL DEFAULT '',
    created_at           TEXT NOT NULL DEFAULT '',
    updated_at           TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    FOREIGN KEY (outsourced_company_id) REFERENCES outsourced_companies (id) ON DELETE CASCADE,
    FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE SET NULL,
    FOREIGN KEY (requested_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (resolved_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_outsourced_company_update_requests_company
    ON outsourced_company_update_requests (company_id, status);

-- RLS: mesma policy restritiva de todo o resto do backend (o backend
-- Python, role postgres, não é afetado — bloqueia só PostgREST direto).
DO $$
DECLARE
  tbl text;
  tbls text[] := ARRAY[
    'outsourced_company_unit_links',
    'outsourced_company_update_requests'
  ];
BEGIN
  FOREACH tbl IN ARRAY tbls LOOP
    CONTINUE WHEN NOT EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = tbl
    );

    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);

    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = tbl
        AND policyname = 'block_direct_api_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY block_direct_api_access ON public.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false)',
        tbl
      );
    END IF;
  END LOOP;
END $$;

-- Backfill: cada empresa terceirizada com Unidade de origem já ganha o
-- próprio vínculo ativo — sem isso, registros criados antes desta migration
-- ficariam sem vínculo nenhum (nem a própria Unidade que cadastrou
-- enxergaria a empresa como "vinculada" depois do deploy).
INSERT INTO outsourced_company_unit_links
    (company_id, outsourced_company_id, unit_id, local_status, activated_at, created_at, updated_at)
SELECT oc.company_id, oc.id, oc.unit_id, 'active',
       to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
       to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
       to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS')
FROM outsourced_companies oc
WHERE oc.unit_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM outsourced_company_unit_links l
    WHERE l.outsourced_company_id = oc.id AND l.unit_id = oc.unit_id
  );
