-- Migration: estoque mínimo individual por Unidade (fatia 1.1D-B0).
--
-- O PROBLEMA
--
-- `epis.minimum_stock` é corporativo: a chave é `epi_id`, sem `unit_id`. Mas a
-- ÚNICA rota que o edita, `POST /api/stock/minimum`, é exclusiva de
-- Administrador Local e Gestor de EPI — os dois perfis travados em UMA
-- Unidade — e valida a visibilidade do EPI *naquela* Unidade antes de gravar
-- na EMPRESA INTEIRA.
--
-- O resultado não é divergência de leitura, é interferência de escrita: o
-- Gestor da Unidade A define 100 e sobrescreve, em silêncio, o mínimo das
-- Unidades B e C. Último a salvar vence, e o operador da outra Unidade passa a
-- operar com um parâmetro que não configurou, sem aviso nenhum.
--
-- A mesma lacuna produz a criticidade errada: comparar o saldo de cada Unidade
-- contra o mínimo da EMPRESA marca como crítica toda Unidade de uma empresa
-- cujo estoque esteja distribuído. Mínimo 100 com 30/30/40 em três Unidades
-- gera três alertas — quando o parâmetro correto de cada Unidade pode ser 40,
-- 25 e 40.
--
-- O MODELO
--
--   estoque corporativo     = SOMA dos saldos das Unidades
--   mínimo corporativo      = APENAS padrão inicial/herdado
--   estoque da Unidade      = unit_epi_stock.quantity
--   mínimo da Unidade       = unit_epi_minimum_stock.minimum_stock
--   criticidade operacional = saldo da Unidade <= mínimo DAQUELA Unidade
--
-- SEM BACKFILL — deliberado.
--
-- A existência da linha É a configuração: `unit_epi_minimum_stock` só tem
-- linha para quem configurou. Criar linhas no backfill faria toda Unidade
-- aparecer como `unit_configured` no dia seguinte à migração, fabricando uma
-- decisão que ninguém tomou e destruindo a distinção que a tabela existe para
-- registrar.
--
-- E o backfill não é necessário para preservar o comportamento: o fallback já
-- resolve para `epis.minimum_stock` com `source = 'company_default'`, então o
-- NÚMERO efetivo continua idêntico ao de hoje — com a verdade histórica
-- intacta. Quando a Unidade salvar seu próprio mínimo pela primeira vez, aí
-- sim nasce a linha, e a auditoria registra a transição
-- `company_default → unit_configured`.
--
-- Aditiva e não-destrutiva: duas tabelas novas, nenhuma coluna existente
-- removida ou alterada. `epis.minimum_stock` permanece, agora com o papel de
-- padrão da empresa. RLS habilitada já nesta migration.

CREATE TABLE IF NOT EXISTS unit_epi_minimum_stock (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         INTEGER NOT NULL,
    unit_id            INTEGER NOT NULL,
    epi_id             INTEGER NOT NULL,
    -- Zero é configuração VÁLIDA ("só me avise ao zerar"), não ausência. Por
    -- isso a resolução testa a existência da LINHA, nunca a truthiness do
    -- valor — o mesmo antipadrão que a fatia 1.1B tirou do saldo de estoque.
    minimum_stock      INTEGER NOT NULL DEFAULT 0,
    created_by_user_id INTEGER,
    updated_by_user_id INTEGER,
    created_at         TEXT NOT NULL DEFAULT '',
    updated_at         TEXT NOT NULL DEFAULT '',
    -- A chave conceitual do parâmetro. É o que impede duas Unidades de
    -- disputarem a mesma linha, que é exatamente o defeito corrigido aqui.
    UNIQUE (company_id, unit_id, epi_id),
    -- CASCATA (e não RESTRICT como em unit_epi_stock): configuração não
    -- sobrevive ao objeto configurado. Saldo é fato e se protege; parâmetro
    -- de uma Unidade apagada não tem a que se referir.
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    FOREIGN KEY (unit_id)    REFERENCES units (id)     ON DELETE CASCADE,
    FOREIGN KEY (epi_id)     REFERENCES epis (id)      ON DELETE CASCADE,
    FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

-- A consulta quente é "qual o mínimo de cada EPI nesta Unidade?", feita a cada
-- listagem de estoque.
CREATE INDEX IF NOT EXISTS idx_unit_epi_minimum_unit
    ON unit_epi_minimum_stock (company_id, unit_id);

-- Auditoria dedicada. `updated_by_user_id` na tabela principal responde apenas
-- "quem mexeu por último"; para HSEQ/NR-6 é preciso demonstrar a trajetória —
-- o mínimo era 10, foi para 30, depois 50, por quem e quando. Este é
-- justamente o parâmetro que até aqui era sobrescrito em silêncio entre
-- Unidades, então o histórico é o ponto, não um extra.
CREATE TABLE IF NOT EXISTS unit_epi_minimum_stock_audit_logs (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             INTEGER NOT NULL,
    unit_id                INTEGER NOT NULL,
    epi_id                 INTEGER NOT NULL,
    action                 TEXT NOT NULL DEFAULT 'set',
    -- NULL = não havia configuração da Unidade; o efetivo vinha do padrão da
    -- empresa. Distinto de 0, que é um mínimo configurado.
    previous_minimum_stock INTEGER,
    new_minimum_stock      INTEGER NOT NULL,
    -- '' | 'unit_configured' | 'company_default'. Registra a transição que
    -- mais importa: herdado -> configurado.
    previous_source        TEXT NOT NULL DEFAULT '',
    actor_user_id          INTEGER,
    -- Ator desnormalizado, como nas demais auditorias do projeto
    -- (ficha_epi_audit_log, purchase_events): o log precisa continuar legível
    -- depois de o usuário ser removido ou trocar de papel.
    actor_name             TEXT NOT NULL DEFAULT '',
    actor_role             TEXT NOT NULL DEFAULT '',
    ip_address             TEXT NOT NULL DEFAULT '',
    user_agent             TEXT NOT NULL DEFAULT '',
    created_at             TEXT NOT NULL,
    FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    FOREIGN KEY (unit_id)    REFERENCES units (id)     ON DELETE CASCADE,
    FOREIGN KEY (epi_id)     REFERENCES epis (id)      ON DELETE CASCADE,
    FOREIGN KEY (actor_user_id) REFERENCES users (id)  ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_unit_epi_minimum_audit_scope
    ON unit_epi_minimum_stock_audit_logs (company_id, unit_id, epi_id, created_at);

-- RLS: mesma policy restritiva do resto do backend. O schema public é exposto
-- pelo PostgREST — sem isto, o parâmetro de estoque de todo tenant seria
-- legível com a chave anon. O backend Python (role postgres) não é afetado.
-- Um bloco por tabela, repetindo o molde de
-- `20260812000000_employee_unit_links.sql` sem variação. A etapa que aplica
-- estas migrations no CI é `continue-on-error: true`, então um deslize de
-- PL/pgSQL passaria em silêncio e só apareceria em produção — não é lugar
-- para inventar forma nova.
DO $$
DECLARE
  tbl text := 'unit_epi_minimum_stock';
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = tbl
  ) THEN
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);

    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = tbl
        AND policyname = 'block_direct_api_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY block_direct_api_access ON public.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false)',
        tbl
      );
    END IF;
  END IF;
END $$;

DO $$
DECLARE
  tbl text := 'unit_epi_minimum_stock_audit_logs';
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = tbl
  ) THEN
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);

    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = tbl
        AND policyname = 'block_direct_api_access'
    ) THEN
      EXECUTE format(
        'CREATE POLICY block_direct_api_access ON public.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false)',
        tbl
      );
    END IF;
  END IF;
END $$;
